---
general:
  healthcheckEvery: 15s
  httpClientTimeout: 5s
  refreshDashboardEvery: 10s
groups:
  - name: Frontend (us-east-1)
    nodes:
      - name: front-1 master host
        endpoint: https://www.example.com/
        expectedPattern: Example
      - name: intranet
        endpoint: https://www.example.com/
        expectedPattern: WillNotFindThis
      - name: front-3
        endpoint: https://www.example.com/
        expectedPattern: Example
  - name: Middleware (us-west-2)
    nodes:
      - name: middleware-1 master host
        endpoint: https://www.example.com/
      - name: middleware-2
        endpoint: https://www.example.com/
      - name: middleware-3
        endpoint: https://www.example.com/
      - name: middleware-4
        endpoint: https://1234567890.example.com/
      - name: middleware-5
        endpoint: https://www.example.com/
  - name: Backend (us-west-2)
    nodes:
      - name: backend-1 master host
        endpoint: https://www.example.com/
      - name: backend-2
        endpoint: https://1234567890.example.com/
      - name: backend-3
        endpoint: https://www.example.com/
